apiVersion: v1
kind: Secret
metadata:
  name: secret-wordpress-a
  namespace: default
  annotations:
    replicator.v1.mittwald.de/replicate-from: client-a/secret-wordpress-a,client-b/secret-wordpress-b
type: kubernetes.io/tls
data:
  tls.crt: crt.pem
  tls.key: key.pem

